### ISSUE TITLE
Posterior plot not working

### ISSUE THREAD

**Issue by LucaMantani** [LHCfitNikhef/smefit_release#42]
The latest commits seem to have broken the production of the posterior plots. Everything works fine in https://github.com/LHCfitNikhef/smefit_release/commit/40f0756d17256b14a0b3ee9375b3096e80d94eaf.

I attach an error message I got

```
[11:42:04] INFO     Analyzing : ['runcard']                                                                                             __init__.py:34
[11:42:05] INFO     Loading dataset : ATLASTTBARTOT7TEV                                                                                  loader.py:133
           INFO     Loading dataset : ATLASTTBARTOT8TEV                                                                                  loader.py:133
           INFO     Loading dataset : ATLAS_TOPDIFF_DILEPT_8TEV_TTMNORM                                                                  loader.py:133
           INFO     Loading dataset : ATLAS_TTBAR_13TEV_DILEPTON_TOTAL                                                                   loader.py:133
           INFO     Loading dataset : ATLAS_TTBAR_13TEV_HADRONIC_2D_TTM_ABSYTTNORM                                                       loader.py:133
           INFO     Loading dataset : ATLAS_TTBAR_13TEV_HADRONIC_TOTAL                                                                   loader.py:133
           INFO     Loading dataset : ATLAS_TTBAR_13TEV_LJETS_TOTAL                                                                      loader.py:133
           INFO     Loading dataset : ATLAS_TTBAR_13TEV_TTMNORM                                                                          loader.py:133
           INFO     Loading dataset : ATLAS_TTBAR_8TEV_LJETS_TOTAL                                                                       loader.py:133
           INFO     Loading dataset : ATLAS_TTB_DIFF_8TEV_LJ_TRAPNORM                                                                    loader.py:133
           INFO     Loading dataset : ATLAS_TTB_DIFF_8TEV_LJ_TTRAPNORM                                                                   loader.py:133
           INFO     Loading dataset : CMSTOPDIFF8TEVTTRAPNORM                                                                            loader.py:133
           INFO     Loading dataset : CMSTTBARTOT13TEV                                                                                   loader.py:133
           INFO     Loading dataset : CMSTTBARTOT5TEV                                                                                    loader.py:133
           INFO     Loading dataset : CMSTTBARTOT7TEV                                                                                    loader.py:133
           INFO     Loading dataset : CMSTTBARTOT8TEV                                                                                    loader.py:133
           INFO     Loading dataset : CMS_TTBAR_13TEV_LJETS_TOTAL                                                                        loader.py:133
           INFO     Loading dataset : CMS_TTBAR_13TEV_TTMNORM                                                                            loader.py:133
           INFO     Loading dataset : CMS_TTBAR_2D_DIFF_MTT_TTRAP_NORM                                                                   loader.py:133
           INFO     Loading dataset : CMS_TTB_DIFF_13TEV_2016_2L_TTMNORM                                                                 loader.py:133
/bin/sh: pandoc: command not found
/bin/sh: pandoc: command not found
Computing SMEFT predictions for each replica of runcard... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
/bin/sh: pandoc: command not found
[11:42:07] INFO     Plotting : chi^2 for each dataset                                                                                    report.py:169
[11:42:15] INFO     Plotting : chi^2 distribution for each replica                                                                       report.py:174
[11:42:17] INFO     Plotting : Confidence Level error bars                                                                               report.py:246
[11:42:19] INFO     Plotting : Posterior histograms                                                                                      report.py:261
Traceback (most recent call last):
  File "/Users/manuelmorales/miniconda3/envs/smefit/bin/smefit", line 6, in <module>
    sys.exit(base_command())
  File "/Users/manuelmorales/miniconda3/envs/smefit/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/manuelmorales/miniconda3/envs/smefit/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/manuelmorales/miniconda3/envs/smefit/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/manuelmorales/miniconda3/envs/smefit/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/manuelmorales/miniconda3/envs/smefit/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/manuelmorales/smefit_release/src/smefit/cli/__init__.py", line 163, in report
    run_report(report_card.absolute())
  File "/Users/manuelmorales/smefit_release/src/smefit/analyze/__init__.py", line 58, in run_report
    report.coefficients(**report_config["coefficients_plots"])
  File "/Users/manuelmorales/smefit_release/src/smefit/analyze/report.py", line 268, in coefficients
    coeff_plt.plot_posteriors(
  File "/Users/manuelmorales/smefit_release/src/smefit/analyze/coefficients_utils.py", line 332, in plot_posteriors
    ax = plt.subplot(grid_size - 1, grid_size, idx + 1)
  File "/Users/manuelmorales/miniconda3/envs/smefit/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1272, in subplot
    key = SubplotSpec._from_subplot_args(fig, args)
  File "/Users/manuelmorales/miniconda3/envs/smefit/lib/python3.10/site-packages/matplotlib/gridspec.py", line 604, in _from_subplot_args
    raise ValueError(
ValueError: num must be 1 <= num <= 12, not 13
```

**Comment by giacomomagni** [comment]
I should have fixed in f887160a
